# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f1032cea999d6342ff17e63936de7e1e0b7ec25d64b1a629948eb944a08b3fe5e946ff6e2552d6099dc57f18ed36422b38f43b770d752ffceaf2526a80652c7
  host: <%= ENV["HOST"] %>
  mailer_username: <%= ENV["MAILER_USERNAME"] %>
  mailer_api_key: <%= ENV["MAILER_API_KEY"] %>
  sentry_dsn: "<%= ENV["SENTRY_DSN"] %>"
  database:
    :username: <%= ENV['DATABASE_USERNAME'] %>
    :password: <%= ENV['DATABASE_PASSWORD'] %>
  instagram_access_token: <%= ENV['INSTAGRAM_ACCESS_TOKEN'] %>

test:
  secret_key_base: 72237ec1081a85beb41ed22747a2f4ef1541fb77c4db110bbddcc83fd77f6c381a99cf42227398129073e05ba094fa0f92863f31144f92d43c1493e2f5696d59
  host: <%= ENV["HOST"] %>
  mailer_username: <%= ENV["MAILER_USERNAME"] %>
  mailer_api_key: <%= ENV["MAILER_API_KEY"] %>
  sentry_dsn: "<%= ENV["SENTRY_DSN"] %>"
  database:
    :username: <%= ENV['DATABASE_USERNAME'] %>
    :password: <%= ENV['DATABASE_PASSWORD'] %>
  instagram_access_token: <%= ENV['INSTAGRAM_ACCESS_TOKEN'] %>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  host: <%= ENV["HOST"] %>
  mailer_username: <%= ENV["MAILER_USERNAME"] %>
  mailer_api_key: <%= ENV["MAILER_API_KEY"] %>
  sentry_dsn: "<%= ENV["SENTRY_DSN"] %>"
  database:
    :username: <%= ENV['DATABASE_USERNAME'] %>
    :password: <%= ENV['DATABASE_PASSWORD'] %>
  instagram_access_token: <%= ENV['INSTAGRAM_ACCESS_TOKEN'] %>
